// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type LearnerState = {
    enabled: boolean;
    /**
     * Send as X-Rdstudio-Token when writing.
     */
    token: string | null;
    dir: string | null;
    events: Array<LearnerEvent>;
    /**
     * Days a week must count for a weekly streak ([learner] week_days, default 4).
     */
    weekDays: number;
};

/**
 * One event: `event` (a name), optionally `concept`, `hash`, `kind` (autodidactic, interactive or ai), `id` and `device`; the server stamps `at`.
 */
export type LearnerEvent = {
    [key: string]: unknown;
};

export type Error = {
    error: string;
};

export type PrivateTour = {
    /**
     * Lowercase letters, digits and dashes.
     */
    name: string;
    title: string;
    description: string;
    /**
     * Markdown: a list whose items each start with a link to a stop, then its narration.
     */
    body: string;
};

export type PrivateTourSave = {
    title: string;
    description?: string;
    body: string;
};

export type TeacherState = {
    /**
     * Whether the teacher folder can be written (the learner record is on).
     */
    enabled: boolean;
    profile: 'topic' | 'codebase' | 'project';
    /**
     * False when guessed: set it in rdstudio.toml ([teacher] profile) or with rdstudio teacher profile.
     */
    profileSet: boolean;
    dir: string | null;
    skills: Array<SkillInfo>;
    /**
     * The teacher folder's commits, newest first.
     */
    history: Array<{
        at: string;
        message: string;
        commit: string;
    }>;
};

export type SkillInfo = {
    name: string;
    description: string;
    /**
     * rdstudio's default, customised here, or written here with no default.
     */
    status: 'default' | 'changed' | 'own';
    /**
     * Customised, and rdstudio's default has changed since.
     */
    defaultChanged: boolean;
};

export type Skill = SkillInfo & {
    /**
     * What the agent reads.
     */
    text: string;
    /**
     * rdstudio's current default.
     */
    default: string | null;
    /**
     * The default the customisation was made from.
     */
    base: string | null;
};

export type TeacherFile = {
    name: 'profile.md' | 'sources.md';
    /**
     * Null until written.
     */
    text: string | null;
    history: Array<{
        at: string;
        message: string;
        commit: string;
    }>;
};

export type TeacherFileSave = {
    text: string;
};

export type AiState = {
    connected: boolean;
    /**
     * Where the key comes from.
     */
    from: 'environment' | 'file' | null;
    /**
     * The model for each job ([teacher.models] in the user config).
     */
    models: {
        [key: string]: string;
    };
    spending: {
        budget: number;
        spent: number;
        left: number;
        warn: boolean;
        stopped: boolean;
        weekStart: string;
        byFeature: {
            [key: string]: number;
        };
        byModel: {
            [key: string]: number;
        };
        byExercise: {
            [key: string]: number;
        };
        calls: number;
    };
};

export type AiConnect = {
    url: string;
};

export type AiCheck = {
    text: string;
    model: string;
    cost: number;
};

export type Draft = {
    exercise: string;
    text: string;
    working: string;
    updated: string | null;
    versions: Array<DraftVersion>;
};

export type DraftVersion = {
    id: string;
    at: string;
    reason: string;
    text: string;
    working: string;
};

export type DraftSave = {
    text: string;
    working?: string;
};

export type DraftKeep = {
    reason?: string;
};

export type DraftRestore = {
    version: string;
};

export type DraftFiled = {
    filed: string | null;
};

export type DraftSubmitted = {
    attempt: string;
};

export type SkillSave = {
    text: string;
};

export type SkillReset = {
    skill: Skill;
};

export type EditState = {
    enabled: boolean;
    /**
     * Send as X-Rdstudio-Token when saving.
     */
    token: string | null;
    /**
     * Who edits are attributed to, such as human:lachlan.
     */
    actor: string;
};

export type NoteHistory = {
    /**
     * Whether the project is a git repository.
     */
    available: boolean;
    commits: Array<{
        hash: string;
        short: string;
        author: string;
        date: string;
        subject: string;
    }>;
    /**
     * The note then against now, as a unified diff, uncommitted changes included.
     */
    diff: string | null;
    base: string | null;
    existed: boolean;
};

export type NoteSource = {
    id: string;
    /**
     * Relative to the knowledge folder.
     */
    path: string;
    /**
     * Of the whole file; send it back as `base` when saving.
     */
    version: string;
    meta: NoteMeta;
    /**
     * The YAML between the --- lines.
     */
    frontmatter: string;
    /**
     * Everything after the frontmatter, verbatim.
     */
    body: string;
};

/**
 * Frontmatter fields.
 */
export type NoteMeta = {
    [key: string]: unknown;
};

export type Moved = {
    moved: Array<{
        from: string;
        to: string;
    }>;
    /**
     * Files whose links were updated.
     */
    rewritten: Array<string>;
};

export type NoteConflict = {
    error: string;
    current: NoteSource & ({
        [key: string]: unknown;
    } | null);
};

export type NoteMove = {
    /**
     * The new id, such as philosophy/motivation.
     */
    to: string;
    /**
     * The note's version; refused if it changed since.
     */
    base?: string | null;
};

export type NoteDeleted = {
    deleted: string;
    /**
     * Notes that linked to it; those links are now broken.
     */
    backlinks: Array<string>;
};

export type FolderMove = {
    from: string;
    to: string;
};

export type FolderDeleted = {
    deleted: string;
    /**
     * The notes deleted with it.
     */
    notes: Array<string>;
    /**
     * Notes elsewhere that linked into it; those links are now broken.
     */
    backlinks: Array<string>;
};

export type NoteSaved = {
    note: NoteSource;
    created: boolean;
    changed: boolean;
    significant: boolean;
};

export type NoteSave = {
    /**
     * The version the edit started from; null creates the note.
     */
    base: string | null;
    body?: string | null;
    /**
     * Fields to set; null removes one.
     */
    meta?: {
        [key: string]: unknown;
    } | null;
};

export type GetApiLearnerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/learner';
};

export type GetApiLearnerErrors = {
    /**
     * Host not allowed
     */
    403: Error;
};

export type GetApiLearnerError = GetApiLearnerErrors[keyof GetApiLearnerErrors];

export type GetApiLearnerResponses = {
    /**
     * The record
     */
    200: LearnerState;
};

export type GetApiLearnerResponse = GetApiLearnerResponses[keyof GetApiLearnerResponses];

export type PostApiLearnerData = {
    body: LearnerEvent;
    headers: {
        'x-rdstudio-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/learner';
};

export type PostApiLearnerErrors = {
    /**
     * Not a valid event
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
    /**
     * Event too large
     */
    413: Error;
    /**
     * Not JSON
     */
    415: Error;
};

export type PostApiLearnerError = PostApiLearnerErrors[keyof PostApiLearnerErrors];

export type PostApiLearnerResponses = {
    /**
     * The event as stored
     */
    200: LearnerEvent;
};

export type PostApiLearnerResponse = PostApiLearnerResponses[keyof PostApiLearnerResponses];

export type GetApiLearnerToursData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/learner/tours';
};

export type GetApiLearnerToursErrors = {
    /**
     * Host not allowed
     */
    403: Error;
};

export type GetApiLearnerToursError = GetApiLearnerToursErrors[keyof GetApiLearnerToursErrors];

export type GetApiLearnerToursResponses = {
    /**
     * The tours
     */
    200: Array<PrivateTour>;
};

export type GetApiLearnerToursResponse = GetApiLearnerToursResponses[keyof GetApiLearnerToursResponses];

export type DeleteApiLearnerToursByNameData = {
    body?: never;
    headers: {
        'x-rdstudio-token': string;
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/api/learner/tours/{name}';
};

export type DeleteApiLearnerToursByNameErrors = {
    /**
     * Not a valid tour
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
    /**
     * Not JSON
     */
    415: Error;
};

export type DeleteApiLearnerToursByNameError = DeleteApiLearnerToursByNameErrors[keyof DeleteApiLearnerToursByNameErrors];

export type DeleteApiLearnerToursByNameResponses = {
    /**
     * Deleted
     */
    200: {
        name: string;
    };
};

export type DeleteApiLearnerToursByNameResponse = DeleteApiLearnerToursByNameResponses[keyof DeleteApiLearnerToursByNameResponses];

export type PutApiLearnerToursByNameData = {
    body: PrivateTourSave;
    headers: {
        'x-rdstudio-token': string;
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/api/learner/tours/{name}';
};

export type PutApiLearnerToursByNameErrors = {
    /**
     * Not a valid tour
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
    /**
     * Not JSON
     */
    415: Error;
};

export type PutApiLearnerToursByNameError = PutApiLearnerToursByNameErrors[keyof PutApiLearnerToursByNameErrors];

export type PutApiLearnerToursByNameResponses = {
    /**
     * The tour as saved
     */
    200: PrivateTour;
};

export type PutApiLearnerToursByNameResponse = PutApiLearnerToursByNameResponses[keyof PutApiLearnerToursByNameResponses];

export type GetApiTeacherData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/teacher';
};

export type GetApiTeacherErrors = {
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
};

export type GetApiTeacherError = GetApiTeacherErrors[keyof GetApiTeacherErrors];

export type GetApiTeacherResponses = {
    /**
     * The teacher
     */
    200: TeacherState;
};

export type GetApiTeacherResponse = GetApiTeacherResponses[keyof GetApiTeacherResponses];

export type DeleteApiTeacherSkillsByNameData = {
    body?: never;
    headers: {
        'x-rdstudio-token': string;
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/api/teacher/skills/{name}';
};

export type DeleteApiTeacherSkillsByNameErrors = {
    /**
     * Bad name or text
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
};

export type DeleteApiTeacherSkillsByNameError = DeleteApiTeacherSkillsByNameErrors[keyof DeleteApiTeacherSkillsByNameErrors];

export type DeleteApiTeacherSkillsByNameResponses = {
    /**
     * Reset
     */
    200: SkillReset;
};

export type DeleteApiTeacherSkillsByNameResponse = DeleteApiTeacherSkillsByNameResponses[keyof DeleteApiTeacherSkillsByNameResponses];

export type GetApiTeacherSkillsByNameData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/teacher/skills/{name}';
};

export type GetApiTeacherSkillsByNameErrors = {
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * No such skill
     */
    404: Error;
};

export type GetApiTeacherSkillsByNameError = GetApiTeacherSkillsByNameErrors[keyof GetApiTeacherSkillsByNameErrors];

export type GetApiTeacherSkillsByNameResponses = {
    /**
     * The skill
     */
    200: Skill;
};

export type GetApiTeacherSkillsByNameResponse = GetApiTeacherSkillsByNameResponses[keyof GetApiTeacherSkillsByNameResponses];

export type PutApiTeacherSkillsByNameData = {
    body: SkillSave;
    headers: {
        'x-rdstudio-token': string;
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/api/teacher/skills/{name}';
};

export type PutApiTeacherSkillsByNameErrors = {
    /**
     * Bad name or text
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
};

export type PutApiTeacherSkillsByNameError = PutApiTeacherSkillsByNameErrors[keyof PutApiTeacherSkillsByNameErrors];

export type PutApiTeacherSkillsByNameResponses = {
    /**
     * Saved
     */
    200: Skill;
};

export type PutApiTeacherSkillsByNameResponse = PutApiTeacherSkillsByNameResponses[keyof PutApiTeacherSkillsByNameResponses];

export type GetApiTeacherFilesByNameData = {
    body?: never;
    path: {
        /**
         * profile.md or sources.md
         */
        name: string;
    };
    query?: never;
    url: '/api/teacher/files/{name}';
};

export type GetApiTeacherFilesByNameErrors = {
    /**
     * Bad name or text
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
};

export type GetApiTeacherFilesByNameError = GetApiTeacherFilesByNameErrors[keyof GetApiTeacherFilesByNameErrors];

export type GetApiTeacherFilesByNameResponses = {
    /**
     * The file
     */
    200: TeacherFile;
};

export type GetApiTeacherFilesByNameResponse = GetApiTeacherFilesByNameResponses[keyof GetApiTeacherFilesByNameResponses];

export type PutApiTeacherFilesByNameData = {
    body: TeacherFileSave;
    headers: {
        'x-rdstudio-token': string;
    };
    path: {
        /**
         * profile.md or sources.md
         */
        name: string;
    };
    query?: never;
    url: '/api/teacher/files/{name}';
};

export type PutApiTeacherFilesByNameErrors = {
    /**
     * Bad name or text
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
};

export type PutApiTeacherFilesByNameError = PutApiTeacherFilesByNameErrors[keyof PutApiTeacherFilesByNameErrors];

export type PutApiTeacherFilesByNameResponses = {
    /**
     * Saved
     */
    200: TeacherFile;
};

export type PutApiTeacherFilesByNameResponse = PutApiTeacherFilesByNameResponses[keyof PutApiTeacherFilesByNameResponses];

export type DeleteApiTeacherAiData = {
    body?: never;
    headers: {
        'x-rdstudio-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/teacher/ai';
};

export type DeleteApiTeacherAiErrors = {
    /**
     * Bad name or text
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
};

export type DeleteApiTeacherAiError = DeleteApiTeacherAiErrors[keyof DeleteApiTeacherAiErrors];

export type DeleteApiTeacherAiResponses = {
    /**
     * Forgotten
     */
    200: AiState;
};

export type DeleteApiTeacherAiResponse = DeleteApiTeacherAiResponses[keyof DeleteApiTeacherAiResponses];

export type GetApiTeacherAiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/teacher/ai';
};

export type GetApiTeacherAiErrors = {
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
};

export type GetApiTeacherAiError = GetApiTeacherAiErrors[keyof GetApiTeacherAiErrors];

export type GetApiTeacherAiResponses = {
    /**
     * The state
     */
    200: AiState;
};

export type GetApiTeacherAiResponse = GetApiTeacherAiResponses[keyof GetApiTeacherAiResponses];

export type PostApiTeacherAiConnectData = {
    body?: never;
    headers: {
        'x-rdstudio-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/teacher/ai/connect';
};

export type PostApiTeacherAiConnectErrors = {
    /**
     * Bad name or text
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
};

export type PostApiTeacherAiConnectError = PostApiTeacherAiConnectErrors[keyof PostApiTeacherAiConnectErrors];

export type PostApiTeacherAiConnectResponses = {
    /**
     * Where to go
     */
    200: AiConnect;
};

export type PostApiTeacherAiConnectResponse = PostApiTeacherAiConnectResponses[keyof PostApiTeacherAiConnectResponses];

export type PostApiTeacherAiCheckData = {
    body?: never;
    headers: {
        'x-rdstudio-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/teacher/ai/check';
};

export type PostApiTeacherAiCheckErrors = {
    /**
     * Bad name or text
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
};

export type PostApiTeacherAiCheckError = PostApiTeacherAiCheckErrors[keyof PostApiTeacherAiCheckErrors];

export type PostApiTeacherAiCheckResponses = {
    /**
     * The reply
     */
    200: AiCheck;
};

export type PostApiTeacherAiCheckResponse = PostApiTeacherAiCheckResponses[keyof PostApiTeacherAiCheckResponses];

export type GetApiTeacherDraftsByIdData = {
    body?: never;
    path: {
        /**
         * The exercise's note id (slashes encoded).
         */
        id: string;
    };
    query?: never;
    url: '/api/teacher/drafts/{id}';
};

export type GetApiTeacherDraftsByIdErrors = {
    /**
     * Bad name or text
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
};

export type GetApiTeacherDraftsByIdError = GetApiTeacherDraftsByIdErrors[keyof GetApiTeacherDraftsByIdErrors];

export type GetApiTeacherDraftsByIdResponses = {
    /**
     * The draft (empty if none)
     */
    200: Draft;
};

export type GetApiTeacherDraftsByIdResponse = GetApiTeacherDraftsByIdResponses[keyof GetApiTeacherDraftsByIdResponses];

export type PutApiTeacherDraftsByIdData = {
    body: DraftSave;
    headers: {
        'x-rdstudio-token': string;
    };
    path: {
        /**
         * The exercise's note id (slashes encoded).
         */
        id: string;
    };
    query?: never;
    url: '/api/teacher/drafts/{id}';
};

export type PutApiTeacherDraftsByIdErrors = {
    /**
     * Bad name or text
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
};

export type PutApiTeacherDraftsByIdError = PutApiTeacherDraftsByIdErrors[keyof PutApiTeacherDraftsByIdErrors];

export type PutApiTeacherDraftsByIdResponses = {
    /**
     * The draft
     */
    200: Draft;
};

export type PutApiTeacherDraftsByIdResponse = PutApiTeacherDraftsByIdResponses[keyof PutApiTeacherDraftsByIdResponses];

export type PostApiTeacherDraftsByIdVersionsData = {
    body: DraftKeep;
    headers: {
        'x-rdstudio-token': string;
    };
    path: {
        /**
         * The exercise's note id (slashes encoded).
         */
        id: string;
    };
    query?: never;
    url: '/api/teacher/drafts/{id}/versions';
};

export type PostApiTeacherDraftsByIdVersionsErrors = {
    /**
     * Bad name or text
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
};

export type PostApiTeacherDraftsByIdVersionsError = PostApiTeacherDraftsByIdVersionsErrors[keyof PostApiTeacherDraftsByIdVersionsErrors];

export type PostApiTeacherDraftsByIdVersionsResponses = {
    /**
     * The draft
     */
    200: Draft;
};

export type PostApiTeacherDraftsByIdVersionsResponse = PostApiTeacherDraftsByIdVersionsResponses[keyof PostApiTeacherDraftsByIdVersionsResponses];

export type PostApiTeacherDraftsByIdRestoreData = {
    body: DraftRestore;
    headers: {
        'x-rdstudio-token': string;
    };
    path: {
        /**
         * The exercise's note id (slashes encoded).
         */
        id: string;
    };
    query?: never;
    url: '/api/teacher/drafts/{id}/restore';
};

export type PostApiTeacherDraftsByIdRestoreErrors = {
    /**
     * Bad name or text
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
};

export type PostApiTeacherDraftsByIdRestoreError = PostApiTeacherDraftsByIdRestoreErrors[keyof PostApiTeacherDraftsByIdRestoreErrors];

export type PostApiTeacherDraftsByIdRestoreResponses = {
    /**
     * The draft
     */
    200: Draft;
};

export type PostApiTeacherDraftsByIdRestoreResponse = PostApiTeacherDraftsByIdRestoreResponses[keyof PostApiTeacherDraftsByIdRestoreResponses];

export type PostApiTeacherDraftsByIdSubmittedData = {
    body: DraftSubmitted;
    headers: {
        'x-rdstudio-token': string;
    };
    path: {
        /**
         * The exercise's note id (slashes encoded).
         */
        id: string;
    };
    query?: never;
    url: '/api/teacher/drafts/{id}/submitted';
};

export type PostApiTeacherDraftsByIdSubmittedErrors = {
    /**
     * Bad name or text
     */
    400: Error;
    /**
     * Cross-origin request, bad token or host not allowed
     */
    403: Error;
    /**
     * The learner record is off
     */
    409: Error;
};

export type PostApiTeacherDraftsByIdSubmittedError = PostApiTeacherDraftsByIdSubmittedErrors[keyof PostApiTeacherDraftsByIdSubmittedErrors];

export type PostApiTeacherDraftsByIdSubmittedResponses = {
    /**
     * Filed
     */
    200: DraftFiled;
};

export type PostApiTeacherDraftsByIdSubmittedResponse = PostApiTeacherDraftsByIdSubmittedResponses[keyof PostApiTeacherDraftsByIdSubmittedResponses];

export type GetApiEditData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/edit';
};

export type GetApiEditErrors = {
    /**
     * Host not allowed
     */
    403: Error;
};

export type GetApiEditError = GetApiEditErrors[keyof GetApiEditErrors];

export type GetApiEditResponses = {
    /**
     * The editing state
     */
    200: EditState;
};

export type GetApiEditResponse = GetApiEditResponses[keyof GetApiEditResponses];

export type GetApiHistoryByIdData = {
    body?: never;
    path: {
        /**
         * The note's id, such as design/model (slashes encoded).
         */
        id: string;
    };
    query: {
        /**
         * An ISO time, such as when you last looked.
         */
        since: string;
    };
    url: '/api/history/{id}';
};

export type GetApiHistoryByIdErrors = {
    /**
     * Not a valid note or time
     */
    400: Error;
    /**
     * Host not allowed
     */
    403: Error;
};

export type GetApiHistoryByIdError = GetApiHistoryByIdErrors[keyof GetApiHistoryByIdErrors];

export type GetApiHistoryByIdResponses = {
    /**
     * The history
     */
    200: NoteHistory;
};

export type GetApiHistoryByIdResponse = GetApiHistoryByIdResponses[keyof GetApiHistoryByIdResponses];

export type DeleteApiNotesByIdData = {
    body?: never;
    headers: {
        'x-rdstudio-token': string;
    };
    path: {
        /**
         * The note's id, such as design/model (slashes encoded).
         */
        id: string;
    };
    query?: {
        base?: string;
    };
    url: '/api/notes/{id}';
};

export type DeleteApiNotesByIdErrors = {
    /**
     * Not a valid request
     */
    400: Error;
    /**
     * Cross-origin request, bad token, host not allowed, or read-only
     */
    403: Error;
    /**
     * The note changed since `base`, or is gone
     */
    409: NoteConflict;
    /**
     * Not JSON
     */
    415: Error;
};

export type DeleteApiNotesByIdError = DeleteApiNotesByIdErrors[keyof DeleteApiNotesByIdErrors];

export type DeleteApiNotesByIdResponses = {
    /**
     * Deleted
     */
    200: NoteDeleted;
};

export type DeleteApiNotesByIdResponse = DeleteApiNotesByIdResponses[keyof DeleteApiNotesByIdResponses];

export type GetApiNotesByIdData = {
    body?: never;
    path: {
        /**
         * The note's id, such as design/model (slashes encoded).
         */
        id: string;
    };
    query?: never;
    url: '/api/notes/{id}';
};

export type GetApiNotesByIdErrors = {
    /**
     * Not a valid note id
     */
    400: Error;
    /**
     * Host not allowed
     */
    403: Error;
    /**
     * No such note
     */
    404: Error;
};

export type GetApiNotesByIdError = GetApiNotesByIdErrors[keyof GetApiNotesByIdErrors];

export type GetApiNotesByIdResponses = {
    /**
     * The note
     */
    200: NoteSource;
};

export type GetApiNotesByIdResponse = GetApiNotesByIdResponses[keyof GetApiNotesByIdResponses];

export type PutApiNotesByIdData = {
    body: NoteSave;
    headers: {
        'x-rdstudio-token': string;
    };
    path: {
        /**
         * The note's id, such as design/model (slashes encoded).
         */
        id: string;
    };
    query?: never;
    url: '/api/notes/{id}';
};

export type PutApiNotesByIdErrors = {
    /**
     * Not a valid edit
     */
    400: Error;
    /**
     * Cross-origin request, bad token, host not allowed, or read-only
     */
    403: Error;
    /**
     * The note changed since `base` (or exists, when creating): the current note is included
     */
    409: NoteConflict;
    /**
     * Too large
     */
    413: Error;
    /**
     * Not JSON
     */
    415: Error;
};

export type PutApiNotesByIdError = PutApiNotesByIdErrors[keyof PutApiNotesByIdErrors];

export type PutApiNotesByIdResponses = {
    /**
     * Saved
     */
    200: NoteSaved;
};

export type PutApiNotesByIdResponse = PutApiNotesByIdResponses[keyof PutApiNotesByIdResponses];

export type PostApiNotesByIdMoveData = {
    body: NoteMove;
    headers: {
        'x-rdstudio-token': string;
    };
    path: {
        /**
         * The note's id, such as design/model (slashes encoded).
         */
        id: string;
    };
    query?: never;
    url: '/api/notes/{id}/move';
};

export type PostApiNotesByIdMoveErrors = {
    /**
     * Not a valid request
     */
    400: Error;
    /**
     * Cross-origin request, bad token, host not allowed, or read-only
     */
    403: Error;
    /**
     * The note changed since `base`, or is gone
     */
    409: NoteConflict;
    /**
     * Not JSON
     */
    415: Error;
};

export type PostApiNotesByIdMoveError = PostApiNotesByIdMoveErrors[keyof PostApiNotesByIdMoveErrors];

export type PostApiNotesByIdMoveResponses = {
    /**
     * Moved
     */
    200: Moved;
};

export type PostApiNotesByIdMoveResponse = PostApiNotesByIdMoveResponses[keyof PostApiNotesByIdMoveResponses];

export type PostApiFoldersMoveData = {
    body: FolderMove;
    headers: {
        'x-rdstudio-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/folders/move';
};

export type PostApiFoldersMoveErrors = {
    /**
     * Not a valid request
     */
    400: Error;
    /**
     * Cross-origin request, bad token, host not allowed, or read-only
     */
    403: Error;
    /**
     * The note changed since `base`, or is gone
     */
    409: NoteConflict;
    /**
     * Not JSON
     */
    415: Error;
};

export type PostApiFoldersMoveError = PostApiFoldersMoveErrors[keyof PostApiFoldersMoveErrors];

export type PostApiFoldersMoveResponses = {
    /**
     * Moved
     */
    200: Moved;
};

export type PostApiFoldersMoveResponse = PostApiFoldersMoveResponses[keyof PostApiFoldersMoveResponses];

export type DeleteApiFoldersByPathData = {
    body?: never;
    headers: {
        'x-rdstudio-token': string;
    };
    path: {
        /**
         * The folder, such as design/old (slashes encoded).
         */
        path: string;
    };
    query?: {
        withNotes?: 'true' | 'false';
    };
    url: '/api/folders/{path}';
};

export type DeleteApiFoldersByPathErrors = {
    /**
     * Not a valid request
     */
    400: Error;
    /**
     * Cross-origin request, bad token, host not allowed, or read-only
     */
    403: Error;
    /**
     * The note changed since `base`, or is gone
     */
    409: NoteConflict;
    /**
     * Not JSON
     */
    415: Error;
};

export type DeleteApiFoldersByPathError = DeleteApiFoldersByPathErrors[keyof DeleteApiFoldersByPathErrors];

export type DeleteApiFoldersByPathResponses = {
    /**
     * Deleted
     */
    200: FolderDeleted;
};

export type DeleteApiFoldersByPathResponse = DeleteApiFoldersByPathResponses[keyof DeleteApiFoldersByPathResponses];
