import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { tokensJson, tokensCss } from './tokens.mjs';
import { todayDoc, workbenchDoc } from './marginalia.mjs';
import { README, COMP_READMES, licences, COVER } from './docs.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');
const proj = path.join(root, 'project');
const harness = path.join(root, 'harness');

const write = (p, s) => { fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, s); };

// tokens
write(path.join(proj, 'tokens.json'), JSON.stringify(tokensJson(), null, 2));

// previews: name -> html
const previews = {
  MarginaliaToday: todayDoc(),
  MarginaliaWorkbench: workbenchDoc({ theme: 'dark' }),
  MarginaliaWorkbenchLight: workbenchDoc({ theme: 'light' }),
};
const extra = path.join(root, 'previews-extra.mjs');
if (fs.existsSync(extra)) Object.assign(previews, (await import(extra)).default);

for (const [name, html] of Object.entries(previews)) {
  write(path.join(proj, 'components', name, 'preview.html'), html);
  // local harness: what the artifact frame preloads (tokens.css) is injected here
  // the frame forces data-theme on <html> to the first theme: simulate that, so the screens must carry their own theme
  const h = html.replace('<head>', `<head><link rel="stylesheet" href="../project/tokens.css">`).replace(/<html lang="en" data-theme="[a-z]+" data-dir="[a-z]+">/, '<html lang="en" data-theme="dark">').replaceAll('../../fonts/', '../project/fonts/');
  write(path.join(harness, `${name}.html`), h);
}
write(path.join(proj, 'README.md'), README);
for (const [n, t] of Object.entries(COMP_READMES)) write(path.join(proj, 'components', n, 'README.md'), t);
for (const [n, t] of Object.entries(licences())) write(path.join(proj, 'assets', 'Licences', n), t);
write(path.join(proj, 'components', 'Cover', 'preview.html'), COVER);
write(path.join(harness, 'Cover.html'), COVER.replace('<head>', '<head><link rel="stylesheet" href="../project/tokens.css">'));
write(path.join(proj, 'tokens.css'), tokensCss('fonts/')); // local only, not published (generated by the page)
console.log('built', Object.keys(previews).join(', '));
